
import  "../src/styles/tailwind.css"



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" class="min-h-full">
      <body class="min-h-full">{children}</body>
    </html>
  );
}
