export const eventInfoList = [
    {
        id:0,
        name:"Anime central",
        description:"Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua",
        imageUrl:"/images/eventImages/animeCentral.jpg",
        keywords:["huge crowd","great cosplays", "lots of mechadise"],
        date: "2024-07-16T14:00:00Z",
    },
    {
        id:1,
        name:"Anime central",
        description:"Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua",
        imageUrl:"/images/eventImages/animeCentral.jpg",
        keywords:["huge crowd","great cosplays", "lots of mechadise"],
        date: "2024-07-16T14:00:00Z",
    },
    {
        id:2,
        name:"Anime central",
        description:"Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua",
        imageUrl:"/images/eventImages/animeCentral.jpg",
        keywords:["huge crowd","great cosplays", "lots of mechadise"],
        date: "2024-07-16T14:00:00Z",
    },
    {
        id:3,
        name:"Anime central",
        description:"Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua",
        imageUrl:"/images/eventImages/animeCentral.jpg",
        keywords:["huge crowd","great cosplays", "lots of mechadise"],
        date: "2024-07-16T14:00:00Z",
    },
    {
        id:4,
        name:"Anime central",
        description:"Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua",
        imageUrl:"/images/eventImages/animeCentral.jpg",
        keywords:["huge crowd","great cosplays", "lots of mechadise"],
        date: "2024-07-16T14:00:00Z",
    },
    {
        id:5,
        name:"Anime central",
        description:"Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua",
        imageUrl:"/images/eventImages/animeCentral.jpg",
        keywords:["huge crowd","great cosplays", "lots of mechadise"],
        date: "2024-07-16T14:00:00Z",
    },
    {
        id:6,
        name:"Anime central",
        description:"Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua",
        imageUrl:"/images/eventImages/animeCentral.jpg",
        keywords:["huge crowd","great cosplays", "lots of mechadise"],
        date: "2024-07-16T14:00:00Z",
    },
    {
        id:7,
        name:"Anime central",
        description:"Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua",
        imageUrl:"/images/eventImages/animeCentral.jpg",
        keywords:["huge crowd","great cosplays", "lots of mechadise"],
        date: "2024-07-16T14:00:00Z",
    },

    {
        id:8,
        name:"Anime central",
        description:"Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua",
        imageUrl:"/images/eventImages/animeCentral.jpg",
        keywords:["huge crowd","great cosplays", "lots of mechadise"],
        date: "2024-07-16T14:00:00Z",
    },
    {
        id:9,
        name:"Anime central",
        description:"Anim aute id magna aliqua ad ad non deserunt sunt. Qui irure qui lorem cupidatat commodo. Elit sunt amet fugiat veniam occaecat fugiat aliqua",
        imageUrl:"/images/eventImages/animeCentral.jpg",
        keywords:["huge crowd","great cosplays", "lots of mechadise"],
        date: "2024-07-16T14:00:00Z",
    },

]

