export const popularEventsData = [
    {
      id: 16,
      title: "Anime Central",
      location: "5555 N River Rd, Rosemont, IL 60018",
      rating: 92,
      attendees: 50000,
      likes: 12000,
      categories: ["cosplay", "panels", "merchandise", "gaming"],
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
      img: "/images/heroImage.jpg",
      website:"https://www.acen.org/",
    },
    {
      id: 26,
      title: "Anime Expo",
      location: "1201 S Figueroa St, Los Angeles, CA 90015",
      rating: 92,
      attendees: 50000,
      likes: 12000,
      categories: ["cosplay", "panels", "merchandise", "gaming"],
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
      img: "/images/heroImage5.jpg",
      website:"https://www.anime-expo.org/",
    },
    {
      id: 36,
      title: "Dream Con",
      location: "500 E. Cesar Chavez St. Austin, TX 78701",
      rating: 92,
      attendees: 50000,
      likes: 12000,
      categories: ["cosplay", "panels", "merchandise", "gaming"],
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
      img: "/images/heroImage3.jpg",
      website:"https://www.dreamconvention.com/",
    },
    {
      id: 46,
      title: "Anime Magic",
      rating: 92,
      location: "5555 N River Rd, Rosemont, IL 60018",
      attendees: 50000,
      likes: 12000,
      categories: ["cosplay", "panels", "merchandise", "gaming"],
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.",
      img: "/images/heroImage4.jpg",
      website:"https://www.animemagic.org/",
    },
  ];

  export const popularEventsCardData = [
    {
      "id": 1,
      "imageUrl": "/images/animeNewsImages/demonSlayer.avif",
      "title": "Anime Expo 2024",
      "location": "Los Angeles, CA",
      "date": "July 3-6, 2024",
      "rating": 4.9,
      "likes": 320,
      "categories": ["Convention", "Cosplay", "Gaming"],
      "description": "Join thousands of fans at the largest anime convention in North America. Experience panels, exclusive merchandise, and cosplay events."
    },
    {
      "id": 2,
      "imageUrl": "/images/animeNewsImages/myHeroAcademia.webp",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 3,
      "imageUrl": "/images/animeNewsImages/attackOnTitan.jpg",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 4,
      "imageUrl": "/images/animeNewsImages/blackClover.webp",
      "title": "Anime Film Festival",
      "location": "San Francisco, CA",
      "date": "October 10-12, 2024",
      "rating": 4.8,
      "likes": 275,
      "categories": ["Film", "Screening", "Panel"],
      "description": "Watch exclusive premieres and fan-favorite anime films, followed by discussions with directors and creators."
    },
    {
      "id": 5,
      "imageUrl": "/images/animeNewsImages/demonSlayer.avif",
      "title": "Anime Expo 2024",
      "location": "Los Angeles, CA",
      "date": "July 3-6, 2024",
      "rating": 4.9,
      "likes": 320,
      "categories": ["Convention", "Cosplay", "Gaming"],
      "description": "Join thousands of fans at the largest anime convention in North America. Experience panels, exclusive merchandise, and cosplay events."
    },
    {
      "id": 6,
      "imageUrl": "/images/animeNewsImages/demonSlayer.avif",
      "title": "Anime Expo 2024",
      "location": "Los Angeles, CA",
      "date": "July 3-6, 2024",
      "rating": 4.9,
      "likes": 320,
      "categories": ["Convention", "Cosplay", "Gaming"],
      "description": "Join thousands of fans at the largest anime convention in North America. Experience panels, exclusive merchandise, and cosplay events."
    },
    {
      "id": 7,
      "imageUrl": "/images/animeNewsImages/demonSlayer.avif",
      "title": "Anime Expo 2024",
      "location": "Los Angeles, CA",
      "date": "July 3-6, 2024",
      "rating": 4.9,
      "likes": 320,
      "categories": ["Convention", "Cosplay", "Gaming"],
      "description": "Join thousands of fans at the largest anime convention in North America. Experience panels, exclusive merchandise, and cosplay events."
    },
    {
      "id": 8,
      "imageUrl": "/images/animeNewsImages/demonSlayer.avif",
      "title": "Anime Expo 2024",
      "location": "Los Angeles, CA",
      "date": "July 3-6, 2024",
      "rating": 4.9,
      "likes": 320,
      "categories": ["Convention", "Cosplay", "Gaming"],
      "description": "Join thousands of fans at the largest anime convention in North America. Experience panels, exclusive merchandise, and cosplay events."
    },
    {
      "id": 9,
      "imageUrl": "/images/animeNewsImages/demonSlayer.avif",
      "title": "Anime Expo 2024",
      "location": "Los Angeles, CA",
      "date": "July 3-6, 2024",
      "rating": 4.9,
      "likes": 320,
      "categories": ["Convention", "Cosplay", "Gaming"],
      "description": "Join thousands of fans at the largest anime convention in North America. Experience panels, exclusive merchandise, and cosplay events."
    },
    {
      "id": 10,
      "imageUrl": "/images/animeNewsImages/demonSlayer.avif",
      "title": "Anime Expo 2024",
      "location": "Los Angeles, CA",
      "date": "July 3-6, 2024",
      "rating": 4.9,
      "likes": 320,
      "categories": ["Convention", "Cosplay", "Gaming"],
      "description": "Join thousands of fans at the largest anime convention in North America. Experience panels, exclusive merchandise, and cosplay events."
    },
    {
      "id": 11,
      "imageUrl": "/images/animeNewsImages/myHeroAcademia.webp",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 12,
      "imageUrl": "/images/animeNewsImages/attackOnTitan.jpg",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 13,
      "imageUrl": "/images/animeNewsImages/myHeroAcademia.webp",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 14,
      "imageUrl": "/images/animeNewsImages/attackOnTitan.jpg",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 15,
      "imageUrl": "/images/animeNewsImages/jujustuKaisen.jpg",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 16,
      "imageUrl": "/images/animeNewsImages/spyFamily.png",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 17,
      "imageUrl": "/images/animeNewsImages/myHeroAcademia.webp",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 18,
      "imageUrl": "/images/animeNewsImages/attackOnTitan.jpg",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 19,
      "imageUrl": "/images/animeNewsImages/jujustuKaisen.jpg",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 20,
      "imageUrl": "/images/animeNewsImages/spyFamily.png",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 21,
      "imageUrl": "/images/animeNewsImages/jujustuKaisen.jpg",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 22,
      "imageUrl": "/images/animeNewsImages/spyFamily.png",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 23,
      "imageUrl": "/images/animeNewsImages/demonSlayer.avif",
      "title": "Anime Expo 2024",
      "location": "Los Angeles, CA",
      "date": "July 3-6, 2024",
      "rating": 4.9,
      "likes": 320,
      "categories": ["Convention", "Cosplay", "Gaming"],
      "description": "Join thousands of fans at the largest anime convention in North America. Experience panels, exclusive merchandise, and cosplay events."
    },
    {
      "id": 24,
      "imageUrl": "/images/animeNewsImages/myHeroAcademia.webp",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 25,
      "imageUrl": "/images/animeNewsImages/attackOnTitan.jpg",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 26,
      "imageUrl": "/images/animeNewsImages/blackClover.webp",
      "title": "Anime Film Festival",
      "location": "San Francisco, CA",
      "date": "October 10-12, 2024",
      "rating": 4.8,
      "likes": 275,
      "categories": ["Film", "Screening", "Panel"],
      "description": "Watch exclusive premieres and fan-favorite anime films, followed by discussions with directors and creators."
    },
    {
      "id": 27,
      "imageUrl": "/images/animeNewsImages/demonSlayer.avif",
      "title": "Anime Expo 2024",
      "location": "Los Angeles, CA",
      "date": "July 3-6, 2024",
      "rating": 4.9,
      "likes": 320,
      "categories": ["Convention", "Cosplay", "Gaming"],
      "description": "Join thousands of fans at the largest anime convention in North America. Experience panels, exclusive merchandise, and cosplay events."
    },
    {
      "id": 28,
      "imageUrl": "/images/animeNewsImages/myHeroAcademia.webp",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 29,
      "imageUrl": "/images/animeNewsImages/attackOnTitan.jpg",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 30,
      "imageUrl": "/images/animeNewsImages/blackClover.webp",
      "title": "Anime Film Festival",
      "location": "San Francisco, CA",
      "date": "October 10-12, 2024",
      "rating": 4.8,
      "likes": 275,
      "categories": ["Film", "Screening", "Panel"],
      "description": "Watch exclusive premieres and fan-favorite anime films, followed by discussions with directors and creators."
    },
    {
      "id": 31,
      "imageUrl": "/images/animeNewsImages/jujustuKaisen.jpg",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 32,
      "imageUrl": "/images/animeNewsImages/spyFamily.png",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 33,
      "imageUrl": "/images/animeNewsImages/jujustuKaisen.jpg",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 34,
      "imageUrl": "/images/animeNewsImages/spyFamily.png",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 35,
      "imageUrl": "/images/animeNewsImages/jujustuKaisen.jpg",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 36,
      "imageUrl": "/images/animeNewsImages/spyFamily.png",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 37,
      "imageUrl": "/images/animeNewsImages/jujustuKaisen.jpg",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 38,
      "imageUrl": "/images/animeNewsImages/spyFamily.png",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
    {
      "id": 39,
      "imageUrl": "/images/animeNewsImages/jujustuKaisen.jpg",
      "title": "Sakura Matsuri",
      "location": "Washington, D.C.",
      "date": "April 13-14, 2024",
      "rating": 4.7,
      "likes": 210,
      "categories": ["Cultural", "Festival", "Music"],
      "description": "Celebrate Japanese culture with traditional performances, food stalls, and a beautiful display of cherry blossoms."
    },
    {
      "id": 40,
      "imageUrl": "/images/animeNewsImages/spyFamily.png",
      "title": "Otaku Party Night",
      "location": "New York, NY",
      "date": "September 20, 2024",
      "rating": 4.6,
      "likes": 150,
      "categories": ["Gathering", "Music", "Dance"],
      "description": "An exciting night of anime music, DJ performances, and dancing with fellow otakus. Dress up as your favorite character!"
    },
  ];
